### ISSUE TITLE
Token text issue

### ISSUE THREAD

**Issue by BenHammoudaAhmed** [Paroca72/sc-gauges#1]
when i setLastTokenOnEnd(true)  numbers don't  match to notches and the last number as you see is far away  from his predicted position.
![untitled-1](https://user-images.githubusercontent.com/29886191/27959583-f779e31c-631f-11e7-97bb-86e1092a8acf.png)

**Comment by Paroca72** [comment]
Hello,

This is the right behavior because the [ScWriter](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-writer/ScWriter.md) divide the path in sectors and inside every sector you can align the text using the [setTextAlign()](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-gauge/ScGauge.md) method (or scc_text_align in XML).

Back to your problem we can solve easily as explained in this [example 2](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/notches.md)

```
gauge.setOnDrawListener(new ScGauge.OnDrawListener() {
        @Override
        public void onBeforeDrawCopy(ScCopier.CopyInfo info) {
            // NOP
        }

        @Override
        public void onBeforeDrawNotch(ScNotches.NotchInfo info) {
            // NOP
        }

        @Override
        public void onBeforeDrawPointer(ScPointer.PointerInfo info) {
            //  NOP
        }

        @Override
        public void onBeforeDrawToken(ScWriter.TokenInfo info) {
            // Center on the notches
            Rect bounds = new Rect();
            info.source.getPainter().getTextBounds(info.text, 0, info.text.length(), bounds);
            info.offset.x = - (bounds.width() / 2) - 1;
        }
    });
```

It is quite important to remember to set this XML property 

```xml
<com.sccomponents.gauges.ScArcGauge
...
scc_text_unbend="true"
</com.sccomponents.gauges.ScArcGauge>
```

for avoid to clip the text 

Please let me know if this solve your case.
Sam

**Comment by BenHammoudaAhmed** [comment]
Hello,
thank for your generosity, your solution is very helpful for me and I really appreciate your guidance, and the time you spent in helping me.
Best Regards,

**Comment by Paroca72** [comment]
You are welcome.
Sam
