### ISSUE TITLE
Adding multiline or 2 line text tokens.

### ISSUE THREAD

**Issue by sarpotdarsaurabh** [Paroca72/sc-gauges#7]
Hello,
Is there any way by which we can add the some part of token text on the new line.. I tried using "abc\n pqr" in token value itself. But it does not seem to work. If any way is there please let me know.

PS- Thanks for this amazing library.Its really helping a lot.

**Comment by Paroca72** [comment]
Hello,

Sorry for the late reply but I have some problem with my PC stuck..
Please try download the latest version (2.6.4).
I added this capability to the ScWriter feature.

Honestly I no have tested a lot this update so I hope not cause mulfunctions in other situations.
Since the "canvas draw text" of android not support the "\n" multiline I had to create a custom function with all related problem about the vertical aligments.. so I hope this will work good. 

Bye
Samuele

**Comment by sarpotdarsaurabh** [comment]
Thank you so much man.. It solved my issue. I will close this issue now. This function seems to work nicely. 

Thank you really.
